### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by MR-Developer20** [Paliverse/DualSenseX#1]
No matter what I do, once the app starts connecting to the controller it just crashes!

**Comment by Paliverse** [comment]
Hello, I'm aware of this issue, currently working on a fix, nasty bug. Are you just connecting to it normally or are you a game dev testing out the commands?

**Comment by MR-Developer20** [comment]
Nah just connecting it normally via usb-c.

**Comment by Paliverse** [comment]
Oh okay, did it happen when the app updated? or you installed Version 1.0.1?

**Comment by Paliverse** [comment]
I have just uploaded the update, can you please open the app and do the update within

**Comment by MR-Developer20** [comment]
> I have just uploaded the update, can you please open the app and do the update within, you can also download the update from releases and open the setup and it will be the latest version automatically.

Ok, I’ll do the update within the app.


> Can you also tell me what operating system your using? Windows or Mac?

lol, windows running on MacBook pro.

**Comment by MR-Developer20** [comment]
> > Oh okay, did it happen when the app updated? or you installed Version 1.0.1?
> 
> Yeah the issue was on 1.0.1 Imma update today to see if it works after which I will write back

Actually, it was running on 1.0.0

**Comment by Paliverse** [comment]
t has come to my attention that a driver must be installed, called ViGEmBus, otherwise the app will crash when trying to connect, I will handle it better in an update so it doesn’t crash when attempting to connect. Please get the latest version of the driver here: https://github.com/ViGEm/ViGEmBus/releases/latest

This is the reason you’re crashing and it’s not working, please install that driver from the link above and you shouldn’t have any more issues :)

**Comment by MR-Developer20** [comment]
Hey, with the recent 1.0.4 it is now working as it should, thanks for the help!

**Comment by Paliverse** [comment]
Happy to hear that!
