### ISSUE TITLE
[BUG]: No haptic feedback when controller emulation is OFF

### ISSUE THREAD

**Issue by KrisCris** [Paliverse/DualSenseX#115]
**Describe the bug**
When I turn controller emulation off to let Steam handle the input, there is no haptic feedback anymore. I do see an option `Disable Controller Vibrations` in the app, which is enabled by default, but the vibration is barely noticeble even with it disabled.

**To Reproduce**
1. Turn off controller emulation
2. play a game on steam

**Expected behavior**
The controller vibrates

**Comment by Paliverse** [comment]
The reason this happens is because the app is talking to the controller to keep whatever effect active, Lights/triggers etc.. when steam sends the vibration to the controller, you'd have your lights reset and triggers reset. In the end, not much i can do, recommend to use the Virtual Xbox360 Emulation mixed with HidHide coming back in 1.5.0, you'd have a much better experience!

**Comment by KrisCris** [comment]
> The reason this happens is because the app is talking to the controller to keep whatever effect active, Lights/triggers etc.. when steam sends the vibration to the controller, you'd have your lights reset and triggers reset. In the end, not much i can do, recommend to use the Virtual Xbox360 Emulation mixed with HidHide coming back in 1.5.0, you'd have a much better experience!

What about emulating dualsense as ds4? I once tried that but end up 2 controllers recognized by steam...

**Comment by Paliverse** [comment]
yeah it's because HidHide is not active. In the next update HidHide is integrated very well that it will hide the controller and then Steam and games will only see 1 controller which is the emulation. you can use either Xbox 360 or DualShock 4

**Comment by KrisCris** [comment]
Oh I see. Then I will probably wait for the next update?
