### ISSUE TITLE
[BUG]: When Try With Native DualSense Supported Game Conflict

### ISSUE THREAD

**Issue by Cyroa** [Paliverse/DualSenseX#124]
Hi, when im try native supported game like Dying Light 2 for extra Haptic Feedback (because default rumble feels like weak to me my opinion), Program and app seems like conflict. 

-Controller Emulation=OFF  (For Addaptive Trigger work native Dualsense and it'll work perfect)

-App audio haptic= ON  (Seems like working in main menu but  when load game in game vibration's like blinking. I think it caused Light Bar thing)
 
-Light Bar features ( I think it caused problem) When main menu this working because game not have programmed led command at main menu but in game they are conflict im think.

My expression this can be caused Light Bar features conflict. Because im look at Pad when im in game just like try game tryin force Native Dualsense Light Bar features on  game and app try forced selected color and switching between Native and Programmed. If u can add program Touchpad Led Disable option maybe we can use with native supported games. Sorry for my language

**Comment by Paliverse** [comment]
This will not work because both the game and DSX are trying to talk to the controller, so they fight each other. If you want the features, you need HidHide and use either an Xbox 360 emulation or DualShock 4 emulation. It’s best to wait for the next version where HidHide is active again configured properly.
