### ISSUE TITLE
[BUG]: Application doesn't work if there's no C: drive

### ISSUE THREAD

**Issue by GuilhermeLeite** [Paliverse/DualSenseX#129]
**Describe the bug**
Mine is a bit of and edge case, but my Windows installation is on E: instead of the usual C:
As such, there's no C: drive anywhere in my setup (unless if I plug in a usb flash drive).
The program refuses to Install or Run in this case, as it can't find the required path 'C:\Temp\DualSenseX'.
With a usb flash drive plugged in (as C:) I've managed to finish the installation process and even use the software, but if it's removed I can't open the program at all.

**To Reproduce**
1. Have a machine without a C: drive
2. Try to Install or Open the application

**Expected behavior**
The application should be able to find the path required or be able to create it. Maybe use System Variables to find the drive in which the OS is installed, instead of a hardcoded path?

**Screenshots**
![image](https://user-images.githubusercontent.com/31831757/155854085-f862369b-7a27-48d8-91ef-3c8b9e0ad244.png)
TL: "Could not find a part of the path 'C:\Temp\DualSenseX'."

**Additional context**
It does not matter if the Dualsense controller is plugged in or not.
Apparently, the test game provided on itch.io also has problems regarding this.

**Comment by Paliverse** [comment]
Hmm, the location is specifically written for C:\temp, pretty much hardwired, I can start making plans for setting a custom path to where the app data should be saved, but can cause issues for UDP mods for the app, Because inside the folder there’s the text file for the port number to be read to make it seamless when running a game with a mod. My best advice is using a C drive or maybe partition a part of your hard drive that’s named C:?
