### ISSUE TITLE
[BUG]: app nothing detecting my controller 

### ISSUE THREAD

**Issue by Brunofabio5** [Paliverse/DualSenseX#174]
**Describe the bug**
the app doesn't find the controller even when it's connected no matter by USB or Bluetooth. just keep searching 

**To Reproduce**
1. open app 
2. Click no matter where 
3. the searching for controller phrase and red dot
**Expected behavior**
the controller to connect. so i can use the app

**Screenshots**

**Additional context**
i started with your beta/free version from here. and i love it a long ago. when i knew that u made a paid one on steam i buy it also to help you
but my app on steam doesn't recognize my controller. keeps searching 
i still use e beta and work 
![16605112156986700848408259310430](https://user-images.githubusercontent.com/111250390/184554921-e501bd62-816f-435e-8642-1cc9051ec783.jpg)

**Comment by Paliverse** [comment]
Hello, you can join the discord server for faster help from me or other members. 

Try re-installing the drivers.

1. uninstall current ones completely, reboot after
2. Then open the app to get the driver missing popup
3. Download/install both ViGEm and HidHide drivers from the app
4. Select no to restart for each install so that you can restart after installing both drivers

if you have issues downloading/installing the drivers you can go to the GitHub page and download them from there.

ViGEm: https://github.com/ViGEm/ViGEmBus/releases/latest

HidHide: https://github.com/ViGEm/HidHide/releases/latest

**Comment by Brunofabio5** [comment]
i already did that. i even Uninstaled the app multiple times

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
