### ISSUE TITLE
[BUG]: Is there really a fake website out there??

### ISSUE THREAD

**Issue by Werfire** [Paliverse/DualSenseX#260]
**Describe the bug**
I decided to install DSX so I searched it up on Google and found this "dualsensex.com" (BE CAREFUL It takes quite long to initially load it, don't know maybe that is the moment when something is happening)
After installing everything was fine, but I decided to also visit GitHub page and was concerned that it says that there is no other websites. So I deleted version I initially installed and downloaded it from here. Comparing them to each other, they are absolutely the same in size up to byte. Is this website just trying to get money from ads?

**Expected behavior**
If that website is legit README should be changed

**Comment by Paliverse** [comment]
Website NOT legit. They have it there generating money from ads, tried to get it shutdown with no success. The files could be the same, but they also host the files, so that can be changed at any moment. Would be easy for them to include something malicious.

**Comment by t3dium** [comment]
> Website NOT legit. They have it there generating money from ads, tried to get it shutdown with no success. The files could be the same, but they also host the files, so that can be changed at any moment. Would be easy for them to include something malicious.

May i suggest submitting the website to urlhaus's blocklists. So that way the fake website would be blocked for a large group of people, such as anyone whose using the ublock origin adblocker with the default filters.

You can also try getting this blocked in [google safebrowsing](https://safebrowsing.google.com/safebrowsing/report_phish/), (i've already submitted a report).

It is a bit concerning how the fake website is the 1st result on searching dualsensex, even more so when considering how professional the website looks.
