### ISSUE TITLE
Keeps disconecting

### ISSUE THREAD

**Issue by Rxhnd** [Paliverse/DualSenseX#39]
I am on W11, using the controller on Bluetooth and everytime I launch DualSenseX it would connect and seconds later it starts disconnecting and reconnecting and saying "Connection Lost Looking for Controller" I got Lime light, Static Color Mode and I got it emulating as a DS4, Normal trigger setting. Any reason why its doing this or any way to solve it?

**Comment by marcusvazdf** [comment]
The same connection-disconnection problem happens with me, however, I use windows 10.

**Comment by Paliverse** [comment]
Have you guys tried a different version? Is it same result?

**Comment by marcusvazdf** [comment]
> Have you guys tried a different version? Is it same result?

Yes. Tested with current and previous version.  I noticed that the control is connected to Windows without intermittence, in the bluetooth properties.  What happens is that the xbox360 controller emulator keeps connecting and disconnecting also in bluetooth properties.  Restarting windows several times sometimes works.  I already uninstalled dualsenseX removing its registry keys and everything else, for a clean reinstallation and it didn't solve.  If there is any way that can help me solve this problem...

**Comment by Maths032** [comment]
I have the same problem, I was playing normally until yesterday. Then it started to connect and disconnect after a few seconds, I have windows 11

**Comment by Maths032** [comment]
> I have the same problem, I was playing normally until yesterday. Then it started to connect and disconnect after a few seconds, I have windows 11


I believe there will be a better solution, but for me it worked very well. Uninstall "HidHideMSI" and restart the computer and the problem solved (at least in my case everything ok)

**Comment by Paliverse** [comment]
Sorry for the late reply, could you try deleting the save file located in C:\Temp\DualSenseX and see if it makes a difference.

**Comment by Verpert** [comment]
This began happening to me after updating this morning, It was working perfectly in Forza Horizon 5 for the past week or so.

Today it's continually saying controller disconnected, please connect a controller, this happens the moment I press any key on the controller, with a press ENTER to continue, interestingly, if I hold down any button on the controller it switches that prompt to press A rather than ENTER. So it's definitely seeing the inputs at times but feels like the emulation drops out on key release.

I tried switching back to the previous version but it's the same now, I cleared the files in C:\Temp\DualSenseX but it's the same.

Running W10

This really is an astonishingly good App so thank you.

**Comment by Verpert** [comment]
Very rapid update, restarting windows several times as someone above suggested, 4th reboot and it's working fine again, so I haven't the foggiest

**Comment by caduhahaha** [comment]
install:
https://github.com/ViGEm/ViGEmBus/releases
https://github.com/ViGEm/HidHide/releases

solved the problem with me, I hope it helps

**Comment by caduhahaha** [comment]
yes, i created the account now so i can write and help, i hope it works there
